development:
  adapter: postgresql
  encoding: unicode
  database: trackr_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: trackr_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: trackr_production
  pool: 5
  username:
  password:
